
[default]
  api_key = "3kkg6k1sla6szuvep1458hhghl2rwobj738glozacnbo4yc08y"
  client_id = "cli_cib5skLHtsVaBgBXE5ShIHzv"
  device_name = "a34f35633290"
  display_name = "Maurice Kherlakian"
  team_name = "Maurice Kherlakian"
