package cmd

import (
	"context"
	"fmt"
	"io"
	"strings"
	"time"

	"github.com/spf13/cobra"

	"github.com/hookdeck/hookdeck-cli/pkg/cmd/outposttypes"
)

// helpSchemaTimeout bounds the one network call --help is allowed to make.
//
// Help must never hang. A cold cache is worth a short fetch because the user has
// already named a --type and clearly wants its fields, but past this point it is
// better to print less than to make someone wait on `--help`.
const helpSchemaTimeout = 2 * time.Second

// writeOutpostDestinationTypeFields renders a destination type's config and
// credential fields.
//
// Shared by 'destination-type get' and the --help augmentation so the two can
// never drift into describing the same schema differently.
func writeOutpostDestinationTypeFields(w io.Writer, schema outposttypes.Schema, showExample bool) {
	for _, group := range []struct {
		flag   string
		fields []outposttypes.Field
	}{
		{"--config", schema.ConfigFields},
		{"--credential", schema.CredentialFields},
	} {
		if len(group.fields) == 0 {
			continue
		}

		fmt.Fprintf(w, "\n%s fields:\n\n", group.flag)
		for _, field := range group.fields {
			label := field.Label
			if label == "" {
				label = field.Key
			}
			fmt.Fprintf(w, "  %-24s %s\n", field.Key, label)
			if notes := describeOutpostField(field); notes != "" {
				fmt.Fprintf(w, "  %-24s (%s)\n", "", notes)
			}
		}
	}

	if showExample {
		fmt.Fprintf(w, "\nExample:\n  %s\n", outpostDestinationExample(schema))
	}
}

// describeOutpostField summarises the constraints the schema states for a field.
func describeOutpostField(field outposttypes.Field) string {
	notes := []string{"optional"}
	if field.Required {
		notes[0] = "required"
	}
	if field.Sensitive {
		notes = append(notes, "sensitive")
	}
	if options := field.OptionValues(); len(options) > 0 {
		notes = append(notes, "one of: "+strings.Join(options, ", "))
	}
	if field.Default != "" {
		notes = append(notes, "default: "+field.Default)
	}
	if field.Pattern != "" {
		notes = append(notes, "pattern: "+field.Pattern)
	}
	if field.Description != "" {
		notes = append(notes, field.Description)
	}
	return strings.Join(notes, "; ")
}

// outpostDestinationExample builds a copy-pasteable create command containing
// exactly the fields the type requires.
func outpostDestinationExample(schema outposttypes.Schema) string {
	var b strings.Builder
	b.WriteString("hookdeck outpost destination create --tenant-id <tenant-id> --type " + schema.Type)

	for _, field := range schema.ConfigFields {
		if field.Required {
			fmt.Fprintf(&b, " \\\n    --config %s=<%s>", field.Key, field.Key)
		}
	}
	for _, field := range schema.CredentialFields {
		if field.Required {
			fmt.Fprintf(&b, " \\\n    --credential %s=<%s>", field.Key, field.Key)
		}
	}

	return b.String()
}

// addOutpostDestinationTypeHelp augments a command's help with the fields for
// whichever --type was given on the command line.
//
// Cobra parses flags before running the help function, so `create --type kafka
// --help` can show exactly that type's fields. Plain `--help` is left untouched,
// which keeps it working offline and before login.
//
// This deliberately does not modify cmd.Long: REFERENCE.md is generated by
// reading Long and the flag definitions directly, so documentation stays
// deterministic no matter what is cached locally.
func addOutpostDestinationTypeHelp(cmd *cobra.Command, destType *string) {
	defaultHelp := cmd.HelpFunc()

	cmd.SetHelpFunc(func(c *cobra.Command, args []string) {
		defaultHelp(c, args)

		if destType == nil || *destType == "" {
			// No type named yet, so there is nothing specific to add. Point at
			// the command that lists them instead.
			fmt.Fprintf(c.OutOrStdout(),
				"\nTip: run this with --type <type> --help to list that type's fields,\nor 'hookdeck outpost destination-type list' to see the available types.\n")
			return
		}

		schema, found := lookupOutpostSchemaForHelp(*destType)
		if !found {
			fmt.Fprintf(c.OutOrStdout(),
				"\nRun 'hookdeck outpost destination-type get %s' to see the fields this type accepts.\n", *destType)
			return
		}

		out := c.OutOrStdout()
		fmt.Fprintf(out, "\nFields for --type %s", schema.Type)
		if schema.Label != "" {
			fmt.Fprintf(out, " (%s)", schema.Label)
		}
		fmt.Fprintln(out)

		writeOutpostDestinationTypeFields(out, schema, false)
	})
}

// lookupOutpostSchemaForHelp resolves a schema for help output without ever
// blocking for long or failing loudly.
//
// The cache is tried first. Only if that misses, and there are credentials to
// use, is a short bounded request made — an unauthenticated `--help` must still
// work, so no attempt is made without a key.
func lookupOutpostSchemaForHelp(destinationType string) (outposttypes.Schema, bool) {
	// Cobra returns flag.ErrHelp before it runs the cobra.OnInitialize hooks, so
	// on the help path the config has not been loaded yet. Without this the
	// client has no base URL or project, and the schema cache — which is keyed on
	// both — would never be found.
	Config.InitConfig()

	client := Config.GetOutpostAPIClient()

	if schema, found := outposttypes.LookupCached(client, destinationType); found {
		return schema, true
	}

	if client.APIKey == "" {
		return outposttypes.Schema{}, false
	}

	ctx, cancel := context.WithTimeout(context.Background(), helpSchemaTimeout)
	defer cancel()

	schemas, err := outposttypes.FetchDestinationTypes(ctx, client)
	if err != nil {
		return outposttypes.Schema{}, false
	}

	return outposttypes.Find(schemas, destinationType)
}
