package hookdeck

import (
	"context"
	"encoding/json"
	"fmt"
	"time"
)

// OutpostDestination represents a delivery destination belonging to a tenant.
//
// The API masks most credentials on read (AWS keys come back as "AKIA****") but
// returns a webhook destination's signing secret in full. That asymmetry is
// deliberate, not an oversight, and it has been raised as a leak more than once:
//
//   - A webhook secret can be generated by the platform. Withholding it would
//     make it unretrievable, and you cannot verify signatures at the receiving
//     end without it.
//   - Every other type's credentials are supplied by the caller at creation.
//     The caller already has them, so returning them adds nothing and only
//     widens exposure.
//
// So the rule is: credentials the platform can produce are readable; credentials
// the caller provided are masked. Before treating this as a bug, check which
// side of that line the field falls on.
//
// Config and Credentials are type-specific, so they stay untyped here and are
// validated against the schemas returned by ListOutpostDestinationTypes rather
// than against hand-written per-type structs.
type OutpostDestination struct {
	ID               string                 `json:"id"`
	Type             string                 `json:"type"`
	Topics           OutpostTopics          `json:"topics"`
	Config           map[string]interface{} `json:"config"`
	Credentials      map[string]interface{} `json:"credentials"`
	Filter           map[string]interface{} `json:"filter,omitempty"`
	DeliveryMetadata map[string]string      `json:"delivery_metadata,omitempty"`
	Metadata         map[string]string      `json:"metadata,omitempty"`
	Target           string                 `json:"target,omitempty"`
	TargetURL        string                 `json:"target_url,omitempty"`
	DisabledAt       *time.Time             `json:"disabled_at"`
	CreatedAt        time.Time              `json:"created_at"`
	UpdatedAt        time.Time              `json:"updated_at"`
}

// Disabled reports whether the destination is currently disabled.
func (d *OutpostDestination) Disabled() bool {
	return d != nil && d.DisabledAt != nil
}

// OutpostDestinationCreateRequest is the body for creating a destination.
// Type and Config are required; the rest depend on the destination type.
type OutpostDestinationCreateRequest struct {
	Type        string                 `json:"type"`
	Topics      OutpostTopics          `json:"topics,omitempty"`
	Config      map[string]interface{} `json:"config,omitempty"`
	Credentials map[string]interface{} `json:"credentials,omitempty"`
	Filter      map[string]interface{} `json:"filter,omitempty"`
	Metadata    map[string]string      `json:"metadata,omitempty"`
}

// OutpostDestinationUpdateRequest is the body for updating a destination.
//
// The endpoint applies JSON merge-patch semantics, so omitted fields are left
// alone — hence omitempty on everything. Filter is the exception: the API
// replaces it wholesale rather than merging into it, which makes sending an
// empty object the way to clear a filter.
//
// Filter is therefore a pointer. On a plain map, omitempty drops any empty map,
// so an explicit --filter '{}' marshalled to nothing and the request became a
// no-op that still reported success — there was no way to clear a filter and no
// sign that clearing had failed. A pointer separates "not supplied" (nil) from
// "supplied as empty" (non-nil, marshals to {}), which is verified to clear it.
//
// Metadata has no equivalent escape hatch: merge-patch semantics mean clearing
// a key requires sending it as null, which a map[string]string cannot express.
// Sending {} leaves existing metadata untouched.
type OutpostDestinationUpdateRequest struct {
	Topics      OutpostTopics           `json:"topics,omitempty"`
	Config      map[string]interface{}  `json:"config,omitempty"`
	Credentials map[string]interface{}  `json:"credentials,omitempty"`
	Filter      *map[string]interface{} `json:"filter,omitempty"`
	Metadata    map[string]string       `json:"metadata,omitempty"`
}

// OutpostObjectPatch prepares a resolved JSON object for a request field that
// has to tell "not supplied" apart from "supplied as empty".
//
// omitempty drops an empty map, so both cases marshal to nothing. Taking the
// address separates them: nil stays absent, and a non-nil empty map marshals
// as {}. Used for a destination filter, where {} clears it, and for a publish
// payload, where {} is a legitimate empty event body.
func OutpostObjectPatch(obj map[string]interface{}) *map[string]interface{} {
	if obj == nil {
		return nil
	}
	return &obj
}

// ListOutpostDestinations retrieves a tenant's destinations, optionally filtered
// by type and topic.
//
// This endpoint is not paginated: it returns a bare JSON array rather than the
// {models, pagination} envelope used elsewhere in this package.
func (c *Client) ListOutpostDestinations(ctx context.Context, tenantID string, types, topics []string) ([]OutpostDestination, error) {
	path, err := apiPath("tenants", tenantID, "destinations")
	if err != nil {
		return nil, err
	}

	query := outpostQuery(nil, map[string][]string{
		"type":   types,
		"topics": topics,
	})

	resp, err := c.Get(ctx, path, query, nil)
	if err != nil {
		return nil, err
	}

	var destinations []OutpostDestination
	if _, err := postprocessJsonResponse(resp, &destinations); err != nil {
		return nil, fmt.Errorf("failed to parse destination list response: %w", err)
	}

	return destinations, nil
}

// GetOutpostDestination retrieves a single destination.
func (c *Client) GetOutpostDestination(ctx context.Context, tenantID, destinationID string) (*OutpostDestination, error) {
	path, err := apiPath("tenants", tenantID, "destinations", destinationID)
	if err != nil {
		return nil, err
	}

	resp, err := c.Get(ctx, path, "", nil)
	if err != nil {
		return nil, err
	}

	var destination OutpostDestination
	if _, err := postprocessJsonResponse(resp, &destination); err != nil {
		return nil, fmt.Errorf("failed to parse destination response: %w", err)
	}

	return &destination, nil
}

// CreateOutpostDestination creates a destination for a tenant.
func (c *Client) CreateOutpostDestination(ctx context.Context, tenantID string, req *OutpostDestinationCreateRequest) (*OutpostDestination, error) {
	path, err := apiPath("tenants", tenantID, "destinations")
	if err != nil {
		return nil, err
	}

	data, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal destination create request: %w", err)
	}

	resp, err := c.Post(ctx, path, data, nil)
	if err != nil {
		return nil, err
	}

	var destination OutpostDestination
	if _, err := postprocessJsonResponse(resp, &destination); err != nil {
		return nil, fmt.Errorf("failed to parse destination response: %w", err)
	}

	return &destination, nil
}

// UpdateOutpostDestination applies a partial update to a destination.
func (c *Client) UpdateOutpostDestination(ctx context.Context, tenantID, destinationID string, req *OutpostDestinationUpdateRequest) (*OutpostDestination, error) {
	path, err := apiPath("tenants", tenantID, "destinations", destinationID)
	if err != nil {
		return nil, err
	}

	data, err := json.Marshal(req)
	if err != nil {
		return nil, fmt.Errorf("failed to marshal destination update request: %w", err)
	}

	// The API uses PATCH here rather than PUT, so this goes through newRequest
	// instead of the Put helper.
	httpReq, err := c.newRequest(ctx, "PATCH", path, data)
	if err != nil {
		return nil, err
	}

	resp, err := c.PerformRequest(ctx, httpReq)
	if err != nil {
		return nil, err
	}

	var destination OutpostDestination
	if _, err := postprocessJsonResponse(resp, &destination); err != nil {
		return nil, fmt.Errorf("failed to parse destination response: %w", err)
	}

	return &destination, nil
}

// DeleteOutpostDestination deletes a destination.
func (c *Client) DeleteOutpostDestination(ctx context.Context, tenantID, destinationID string) error {
	path, err := apiPath("tenants", tenantID, "destinations", destinationID)
	if err != nil {
		return err
	}

	req, err := c.newRequest(ctx, "DELETE", path, nil)
	if err != nil {
		return err
	}

	resp, err := c.PerformRequest(ctx, req)
	if err != nil {
		return err
	}
	defer resp.Body.Close()

	return nil
}

// EnableOutpostDestination re-enables a disabled destination.
func (c *Client) EnableOutpostDestination(ctx context.Context, tenantID, destinationID string) (*OutpostDestination, error) {
	return c.setOutpostDestinationEnabled(ctx, tenantID, destinationID, "enable")
}

// DisableOutpostDestination stops delivery to a destination without deleting it.
func (c *Client) DisableOutpostDestination(ctx context.Context, tenantID, destinationID string) (*OutpostDestination, error) {
	return c.setOutpostDestinationEnabled(ctx, tenantID, destinationID, "disable")
}

func (c *Client) setOutpostDestinationEnabled(ctx context.Context, tenantID, destinationID, action string) (*OutpostDestination, error) {
	path, err := apiPath("tenants", tenantID, "destinations", destinationID, action)
	if err != nil {
		return nil, err
	}

	resp, err := c.Put(ctx, path, []byte("{}"), nil)
	if err != nil {
		return nil, err
	}

	var destination OutpostDestination
	if _, err := postprocessJsonResponse(resp, &destination); err != nil {
		return nil, fmt.Errorf("failed to parse destination response: %w", err)
	}

	return &destination, nil
}
