package hookdeck

import (
	"errors"
	"fmt"
	"net/url"
	"strings"
)

// ErrInvalidResourceID reports an identifier that cannot be used as a URL path
// segment. It is deliberately distinct from ErrRequestPathRejected so that a
// failure can be attributed to the call site's own validation rather than to
// the request layer's final check.
var ErrInvalidResourceID = errors.New("invalid resource identifier")

// pathSegment escapes id for use as a single URL path segment.
//
// Identifiers reach this package from command arguments and MCP tool calls, so
// they are untrusted input. A value that would name something other than the
// resource it appears to name — an empty string, "." or "..", or anything
// containing a path separator — is rejected rather than escaped: resolving such
// a value against the base URL rewrites the path, so the request would address
// a different resource from the one the caller named and reported.
//
// Everything else is percent-escaped. Some identifiers, tenant IDs in
// particular, are chosen by the operator rather than generated by the API, so
// they can legitimately contain characters that have meaning in a URL.
func pathSegment(id string) (string, error) {
	switch {
	case id == "":
		return "", fmt.Errorf("%w: an id is required, but an empty value was given", ErrInvalidResourceID)
	case id == "." || id == "..":
		return "", fmt.Errorf("%w: %q refers to a position in the URL rather than to a resource", ErrInvalidResourceID, id)
	case strings.ContainsAny(id, "/\\"):
		return "", fmt.Errorf("%w: %q contains a path separator, so it does not name a single resource", ErrInvalidResourceID, id)
	}

	return url.PathEscape(id), nil
}

// apiPath builds a request path from APIPathPrefix and the given segments,
// validating and escaping each one with pathSegment.
//
// Every endpoint that interpolates a caller-supplied value into its path builds
// it here, so the validation cannot be skipped by forgetting to escape one
// argument out of several.
func apiPath(segments ...string) (string, error) {
	parts := make([]string, 0, len(segments)+1)
	parts = append(parts, APIPathPrefix)

	for _, segment := range segments {
		escaped, err := pathSegment(segment)
		if err != nil {
			return "", err
		}
		parts = append(parts, escaped)
	}

	return strings.Join(parts, "/"), nil
}
